fix ordering of tasks so concourse can start up
Fixes #91

Without this, if `CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS` is defined, we can see the following error

```
cat /var/log/concourse/concourseci_web.log

error: invalid argument for flag `--base-resource-type-defaults' (expected flag.File): stat /mnt/concourse/resource-type-defaults.yml: no such file or directory
```

Due to concourse attempting to start up before that configuration file
was written. This PR just changes the order.